docker-build-master:
  image: docker:latest
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - docker build --pull -t "$IMAGE_TAG" .
    - docker tag $CI_REGISTRY_IMAGE latest
    - docker push $IMAGE_TAG
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master